print(" Operator ")
print(5+6)
print(15-6)
print(15*6)
print(15/6)
print(15//6)
print(5%3)
print(2**4)

print("------------Calculator----------")
x = int(input("Enter an first number-\t"))
y = int(input("Enter an second number-\t"))
print("Sum of first and second number is\t",x+y)
print("Substraction of first and second number is\t",x-y)
print("Multiplication of first and second number is\t",x*y)
print("Division of first and second number is\t",x/y)
print("Exponantial value of x of y is\t",x**y)
print("Modulus of",x,"and",y,"is", x%y)
print("Floor Division of",x,"and",y,"is", x//y)
